/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'apple-blue': '#007AFF',
        'apple-blue-hover': '#0066CC',
        'apple-red': '#FF3B30',
        'apple-orange': '#FF9500',
        'apple-yellow': '#FFCC00',
        'apple-green': '#4CD964',
        'apple-purple': '#5856D6',
        'apple-pink': '#FF2D55',
        'apple-teal': '#5AC8FA',
        'apple-gray': '#8E8E93',
        'apple-gray-light': '#F2F2F7',
        'apple-gray-dark': '#C7C7CC',
        'apple-gray-darker': '#636366',
        'apple-divider': '#0000000D',
        'apple-divider-light': '#FFFFFF60',
        'apple-bg': '#F5F5F7',
        'apple-card': '#FFFFFF',
        'aurora-blue': 'rgba(162, 210, 255, 0.5)',
        'aurora-purple': 'rgba(200, 180, 255, 0.4)',
        'aurora-pink': 'rgba(255, 180, 200, 0.3)',
        'glass-white': 'rgba(255, 255, 255, 0.85)',
        'glass-gray': 'rgba(245, 245, 247, 0.7)',
      },
      fontFamily: {
        sans: ['-apple-system', 'BlinkMacSystemFont', 'SF Pro Display', 'SF Pro Text', 'PingFang SC', 'Helvetica Neue', 'sans-serif'],
      },
      borderRadius: {
        'apple': '12px',
        'apple-sm': '8px',
        'apple-md': '10px',
        'apple-lg': '16px',
        'apple-xl': '20px',
        'apple-2xl': '24px',
        'apple-3xl': '28px',
        'apple-full': '9999px',
      },
      boxShadow: {
        'apple': '0 4px 20px rgba(0, 0, 0, 0.08)',
        'apple-sm': '0 2px 8px rgba(0, 0, 0, 0.06)',
        'apple-lg': '0 8px 32px rgba(0, 0, 0, 0.12)',
        'apple-xl': '0 12px 48px rgba(0, 0, 0, 0.16)',
        'apple-glow': '0 0 20px rgba(0, 122, 255, 0.25)',
        'apple-glow-strong': '0 0 30px rgba(0, 122, 255, 0.4)',
        'apple-inset': 'inset 0 1px 0 rgba(255, 255, 255, 0.5)',
        'apple-card': '0 1px 3px rgba(0, 0, 0, 0.05), 0 4px 12px rgba(0, 0, 0, 0.05)',
        'apple-card-hover': '0 2px 6px rgba(0, 0, 0, 0.08), 0 8px 24px rgba(0, 0, 0, 0.08)',
      },
      transitionTimingFunction: {
        'spring': 'cubic-bezier(0.25, 1, 0.5, 1)',
        'spring-fast': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      animation: {
        'slide-in': 'slideIn 0.3s cubic-bezier(0.25, 1, 0.5, 1)',
        'float-slow': 'floatSlow 20s ease-in-out infinite',
        'float-medium': 'floatMedium 24s ease-in-out infinite',
        'float-fast': 'floatFast 18s ease-in-out infinite',
        'fade-in-up': 'fadeInUp 0.4s cubic-bezier(0.25, 1, 0.5, 1)',
        'fade-in-up-fast': 'fadeInUp 0.25s cubic-bezier(0.25, 1, 0.5, 1)',
        'pulse-glow': 'pulseGlow 3s ease-in-out infinite',
        'scale-in': 'scaleIn 0.35s cubic-bezier(0.25, 1, 0.5, 1)',
        'slide-up': 'slideUp 0.4s cubic-bezier(0.25, 1, 0.5, 1)',
        'slide-down': 'slideDown 0.25s cubic-bezier(0.25, 1, 0.5, 1)',
        'slide-left': 'slideLeft 0.2s cubic-bezier(0.25, 1, 0.5, 1)',
        'slide-right': 'slideRight 0.3s cubic-bezier(0.25, 1, 0.5, 1)',
        'bounce-in': 'bounceIn 0.5s cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      keyframes: {
        slideIn: {
          '0%': { transform: 'translateX(100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        floatSlow: {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)' },
          '33%': { transform: 'translate(2%, -2%) scale(1.02)' },
          '66%': { transform: 'translate(-2%, 2%) scale(0.98)' },
        },
        floatMedium: {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)' },
          '33%': { transform: 'translate(-1.5%, 1.5%) scale(1.01)' },
          '66%': { transform: 'translate(1.5%, -1.5%) scale(0.99)' },
        },
        floatFast: {
          '0%, 100%': { transform: 'translate(0, 0)' },
          '50%': { transform: 'translate(1%, 1%)' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        pulseGlow: {
          '0%, 100%': { opacity: '0.5', transform: 'scale(1)' },
          '50%': { opacity: '0.7', transform: 'scale(1.03)' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.92)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(100%)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-12px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideLeft: {
          '0%': { transform: 'translateX(8px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideRight: {
          '0%': { transform: 'translateX(-100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        bounceIn: {
          '0%': { transform: 'scale(0.3)', opacity: '0' },
          '50%': { transform: 'scale(1.05)' },
          '70%': { transform: 'scale(0.9)' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
      backdropBlur: {
        xs: '2px',
      },
    },
  },
  plugins: [],
}
